### ISSUE TITLE
Integration with Storybook 6

### ISSUE THREAD

**Issue by amcdnl** [kevin940726/remark-codesandbox#14]
How does this integrate with the new storybook? https://storybook.js.org/docs/react/configure/webpack

https://github.com/reaviz/reaviz/blob/master/.storybook/main.js#L23

**Comment by kevin940726** [comment]
Just integrate it like everything else :)

I can send a example PR if that's cool to you!

**Comment by kevin940726** [comment]
@amcdnl And... it's done :)! https://github.com/reaviz/reaviz/pull/8

**Comment by amcdnl** [comment]
THANK YOU!
