### ISSUE TITLE
Yarn install is not working

### ISSUE THREAD

**Issue by washingtonsoares** [kevin940726/remark-codesandbox#4]
Apparently the installation is not working on the master

![image](https://user-images.githubusercontent.com/5726140/74057947-bc9bd100-49c3-11ea-8e97-565dca9adaf5.png)

I've tried with [this commit ](https://github.com/kevin940726/remark-codesandbox/commit/4103d6b7cce3c239fc7c7b74a522809404e22de7) and it works fine.

![image](https://user-images.githubusercontent.com/5726140/74058114-1ac8b400-49c4-11ea-9839-5b2618bf00a7.png)

**Comment by kevin940726** [comment]
Hmmm probably something wrong with yarn 2, I’ll try to debug it later. Thx for the issue!

What version of node are you running? It is only affecting development, right? Is `gatsyby-remark-inline-codesandbox` working for you 😉?

**Comment by washingtonsoares** [comment]
> What version of node are you running? 

I'm using `yarn 1.19.1` and `node v10.17.0`

> It is only affecting development, right? 

Yes!

> Is `gatsyby-remark-inline-codesandbox` working for you 😉?

Yes! 😍 

Thanks for the support!

**Comment by kevin940726** [comment]
This is weird, I cannot seem to reproduce it. Do you have a error log file or something like that? 🤔

**Comment by washingtonsoares** [comment]
I just removed the yarn.lock file and everything worked 😄

**Comment by kevin940726** [comment]
Cool 👍, still don't know why it happened though 😂. I'm gonna close this, tell me if it happens again :)
