### ISSUE TITLE
Can we make the button to open a new window (instead of navigating and exiting the site)?

### ISSUE THREAD

**Issue by kuworking** [kevin940726/remark-codesandbox#6]
Can we make the button to open a new window (instead of navigating and exiting the site)?

The use case is to prevent the user to abandon the site by clicking the button

**Comment by kevin940726** [comment]
Of course you can!

It depends on your setup though. What environment are you using? In some environment, markdown links defaults to open in the current tab. If you want to override to make it render in a new tab, you might need to create a wrapper for that.

I added this in [my own blog](https://kaihao.dev/posts/One-fun-trick-to-observe-elements-in-realtime-without-MutationObserver), which is a Gatsby blog. I'm using `meta` mode and parse the meta myself in the [application code](https://github.com/kevin940726/kaihao.dev/blob/master/src/components/Highlight.js#L187-L189).

Maybe you could do something similar with additional plugins ([remark-external-links](https://github.com/remarkjs/remark-external-links)), just make sure to add them after `remark-codesandbox`.

**Comment by kuworking** [comment]
Thanks @kevin940726 

I can see what you do to modify the tag, very neat 🙌🙌 

(off-topic) I can see that you dynamically import the languages if required, didn't think about it (still consider imports as non-dynamic), what's the impact (in your opinion) of always importing them "just in case"?

**Comment by kevin940726** [comment]
@kuworking Thanks!

It’s just for the sake of doing code splitting, so that the client wouldn’t have to download unnecessary language file.

**Comment by kuworking** [comment]
(following on the dynamic import discussion) I'm implementing your code splitting strategy but I cannot import the module, I can only require it

```js
if (language === 'php') require('prismjs/components/prism-php')
// or
if (language === 'php') import('prismjs/components/prism-php')
```

First line works, second line does not (it does work in your code thought)

**Comment by kevin940726** [comment]
Maybe it's a problem with environment settings? Are you using Gatsby?

This is getting off-topic though 😂, either way I'm happy to help, but perhaps there's better resources out there though 😉.

**Comment by kuworking** [comment]
Yes, it's all gatsby here, and I was just hoping for a fast answer, but if you haven't done anything specific about this, then it's too much off-topic :)

Thanks again!

**Comment by kevin940726** [comment]
@kuworking np! If you still couldn’t find the problem, feel free to DM me on Twitter with the reproducible repo ;)
